# Generated by Django 6.0.1 on 2026-01-11 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_comments_item_vendor_purchaseorder_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseorder'),
        ),
    ]
